namespace OpenNV.Runtime.Content;

internal sealed record FalloutCompiledCommandDeclaration(string Name, bool RequiresReference,
    int Required, IReadOnlyList<byte> Parameters, bool VanillaArguments);

// Neutral original vanilla API identities/parameter categories. Declaration
// coverage is separate from the shared runtime owning the reached effect.
internal static class FalloutCompiledCommandDeclarations
{
    private static readonly System.Runtime.CompilerServices.ConditionalWeakTable<RuntimeLiveContentSource,
        FalloutNativeScriptCommandCatalogue> SourceCommands = new();
    private static readonly IReadOnlyDictionary<ushort, FalloutCompiledCommandDeclaration> Commands =
        new Dictionary<ushort, FalloutCompiledCommandDeclaration>
        {
            [0x1137] = new("ModPCMiscStat", false, 2, [41, 1], true),
            [0x1138] = new("GetPCMiscStat", false, 1, [41], true),
            [0x1001] = new("GetDistance", true, 1, [4], true),
            [0x1002] = new("AddItem", true, 2, [50, 1, 1], true),
            [0x1005] = new("GetLocked", true, 0, [], true),
            [0x1006] = new("GetPos", true, 1, [8], true),
            [0x1008] = new("GetAngle", true, 1, [8], true),
            [0x100c] = new("GetSecondsPassed", false, 0, [], true),
            [0x100d] = new("Activate", true, 0, [4, 1], true),
            [0x100e] = new("GetActorValue", true, 1, [5], true),
            [0x100f] = new("SetActorValue", true, 2, [5, 1], true),
            [0x1010] = new("ModActorValue", true, 2, [5, 1], true),
            [0x1012] = new("GetCurrentTime", false, 0, [], true),
            [0x1013] = new("PlayGroup", true, 2, [10, 1], true),
            [0x1016] = new("StartCombat", true, 1, [6], true),
            [0x1017] = new("StopCombat", true, 0, [], true),
            [0x101f] = new("GetButtonPressed", false, 0, [], true),
            [0x1020] = new("GetInSameCell", true, 1, [4], true),
            [0x1021] = new("Enable", true, 0, [1], true),
            [0x1022] = new("Disable", true, 0, [1], true),
            [0x1023] = new("GetDisabled", true, 0, [], true),
            [0x1024] = new("MenuMode", false, 0, [1], true),
            [0x1026] = new("PlaySound", false, 1, [12, 1], true),
            [0x1028] = new("GetVampire", true, 0, [], true),
            [0x102d] = new("GetDetected", true, 1, [6], true),
            [0x102e] = new("GetDead", true, 0, [], true),
            [0x102f] = new("GetItemCount", true, 1, [50], true),
            [0x1032] = new("GetTalkedToPC", true, 0, [], true),
            [0x1033] = new("Say", true, 1, [13, 1, 25, 1, 1], true),
            [0x1034] = new("SayTo", true, 2, [6, 13, 1, 1], true),
            [0x1036] = new("StartQuest", false, 1, [14], true),
            [0x1037] = new("StopQuest", false, 1, [14], true),
            [0x1038] = new("GetQuestRunning", false, 1, [14], true),
            [0x1039] = new("SetStage", false, 2, [14, 23], true),
            [0x103a] = new("GetStage", false, 1, [14], true),
            [0x103b] = new("GetStageDone", false, 2, [14, 23], true),
            [0x1041] = new("GetLockLevel", true, 0, [], true),
            [0x1043] = new("GetInCell", true, 1, [9], true),
            [0x1046] = new("GetIsSex", true, 1, [18], true),
            [0x1047] = new("GetInFaction", true, 1, [17], true),
            [0x1048] = new("GetIsID", true, 1, [21], true),
            [0x1049] = new("GetFactionRank", true, 1, [17], true),
            [0x104d] = new("GetRandomPercent", false, 0, [], true),
            [0x1050] = new("GetLevel", true, 0, [], true),
            [0x1052] = new("RemoveItem", true, 2, [50, 1, 1], true),
            [0x1054] = new("GetDeadCount", false, 1, [25], true),
            [0x1059] = new("ShowMessage", false, 1, [49], false),
            [0x105a] = new("SetAlert", true, 1, [1], true),
            [0x105c] = new("Look", true, 1, [4, 1], true),
            [0x105d] = new("StopLook", true, 0, [], true),
            [0x105e] = new("EvaluatePackage", true, 0, [], true),
            [0x1060] = new("EnablePlayerControls", false, 0, [1, 1, 1, 1, 1, 1, 1], true),
            [0x1061] = new("DisablePlayerControls", false, 0, [1, 1, 1, 1, 1, 1, 1], true),
            [0x1063] = new("GetHeadingAngle", true, 1, [4], true),
            [0x1068] = new("CreateDetectionEvent", true, 2, [4, 1, 1], true),
            [0x1069] = new("IsActionRef", true, 1, [4], true),
            [0x1072] = new("Lock", true, 0, [1, 1], true),
            [0x1073] = new("UnLock", true, 0, [1], true),
            [0x1078] = new("SetEnemy", false, 2, [17, 17, 1, 1], true),
            [0x1079] = new("SetAlly", false, 2, [17, 17, 1, 1], true),
            [0x1088] = new("GetIsReference", true, 1, [4], true),
            [0x1089] = new("SetFactionRank", true, 2, [17, 1], true),
            [0x108b] = new("KillActor", true, 0, [6, 1, 1], true),
            [0x108d] = new("IsTalking", true, 0, [], true),
            [0x1097] = new("AddScriptPackage", true, 1, [29], true),
            [0x1098] = new("RemoveScriptPackage", true, 0, [], true),
            [0x109d] = new("GetOpenState", true, 0, [], true),
            [0x109e] = new("MoveTo", true, 1, [4, 2, 2, 2], true),
            [0x109f] = new("GetSitting", true, 0, [], true),
            [0x10a1] = new("GetIsCurrentPackage", true, 1, [29], true),
            [0x10ad] = new("RemoveAllItems", true, 0, [26, 1, 1], true),
            [0x10b1] = new("SetCombatStyle", true, 0, [30], true),
            [0x10c0] = new("GetIgnoreCrime", false, 0, [], true),
            [0x10cc] = new("SetDestroyed", true, 1, [1], true),
            [0x10cd] = new("GetActionRef", true, 0, [], true),
            [0x10ce] = new("GetSelf", true, 0, [], true),
            [0x10da] = new("ShowRaceMenu", false, 0, [], true),
            [0x10dd] = new("SetOpenState", true, 1, [1], true),
            [0x10e7] = new("SetInChargen", false, 1, [1], true),
            [0x10ee] = new("EquipItem", true, 1, [3, 1, 1], true),
            [0x10ef] = new("UnequipItem", true, 1, [3, 1, 1], true),
            [0x10f1] = new("SetUnconscious", false, 1, [1], true),
            [0x10f2] = new("GetUnconscious", true, 0, [], true),
            [0x10f3] = new("SetRestrained", false, 1, [1], true),
            [0x1101] = new("SCAOnActor", true, 0, [], true),
            [0x110e] = new("ForceActorValue", true, 2, [5, 1], true),
            [0x1114] = new("PlayBink", false, 1, [0, 1, 1, 1, 1], true),
            [0x1115] = new("GetBaseActorValue", true, 1, [5], true),
            [0x1117] = new("SetOwnership", true, 0, [35], true),
            [0x1121] = new("IsInCombat", true, 0, [], true),
            [0x1128] = new("IsAnimPlaying", true, 0, [10], true),
            [0x112c] = new("IsInInterior", true, 0, [], true),
            [0x112d] = new("ForceWeather", false, 1, [33, 1], true),
            [0x1133] = new("SetLevel", true, 1, [1, 1, 1, 1], true),
            [0x1135] = new("IsXBox", false, 0, [], true),
            [0x113c] = new("SetScale", true, 1, [2], true),
            [0x1150] = new("ResetHealth", true, 0, [], true),
            [0x1152] = new("GetIgnoreFriendlyHits", true, 0, [], true),
            [0x1158] = new("ReleaseWeatherOverride", false, 0, [], true),
            [0x115e] = new("Autosave", false, 0, [], true),
            [0x116b] = new("GetLinkedRef", true, 0, [], true),
            [0x1174] = new("IsInList", true, 1, [37], true),
            [0x1176] = new("AddPerk", true, 1, [39, 1], true),
            [0x1177] = new("RewardXP", false, 1, [1], true),
            [0x117c] = new("AddNote", false, 1, [40], true),
            [0x117f] = new("AddToFaction", true, 2, [17, 1], true),
            [0x1180] = new("RemoveFromFaction", true, 1, [17], true),
            [0x1191] = new("ApplyImageSpaceModifier", false, 1, [42, 2], true),
            [0x1192] = new("RemoveImageSpaceModifier", false, 1, [42, 2], true),
            [0x11a2] = new("SetObjectiveCompleted", false, 3, [14, 1, 1], true),
            [0x11a3] = new("SetObjectiveDisplayed", false, 3, [14, 1, 1], true),
            [0x11a4] = new("GetObjectiveCompleted", false, 2, [14, 1], true),
            [0x11a5] = new("GetObjectiveDisplayed", false, 2, [14, 1], true),
            [0x11a8] = new("RemovePerk", true, 1, [39, 1], true),
            [0x11ad] = new("CompleteAllObjectives", false, 1, [14], true),
            [0x11bb] = new("MarkForDelete", true, 0, [], true),
            [0x11bc] = new("AddItemHealthPercent", true, 3, [3, 1, 2, 1], true),
            [0x11c1] = new("HasPerk", true, 1, [39, 1], true),
            [0x11c5] = new("SetPlayerTeammate", true, 1, [1], true),
            [0x11c6] = new("GetPlayerTeammate", true, 0, [], true),
            [0x11d4] = new("GetBroadcastState", true, 0, [], true),
            [0x11d5] = new("SetBroadcastState", true, 1, [1], true),
            [0x11d6] = new("StartRadioConversation", true, 0, [13], true),
            [0x11df] = new("MatchFaceGeometry", true, 2, [6, 1], true),
            [0x11e1] = new("GetPlayerName", false, 0, [], true),
            [0x11e4] = new("AgeRace", true, 1, [1], true),
            [0x11e5] = new("MatchRace", true, 1, [6], true),
            [0x11e6] = new("SetPCYoung", false, 1, [1], true),
            [0x11e7] = new("SexChange", false, 0, [18, 1], true),
            [0x11ec] = new("GetMapMarkerVisible", true, 0, [], true),
            [0x11ed] = new("ResetInventory", true, 0, [], true),
            [0x11ef] = new("GetPermanentActorValue", true, 1, [5], true),
            [0x11fa] = new("ResetAI", true, 0, [], true),
            [0x11ff] = new("PlayMusic", false, 1, [54], true),
            [0x1200] = new("SetLocationSpecificLoadScreensOnly", false, 1, [1], true),
            [0x1201] = new("ResetPipboyManager", false, 0, [], true),
            [0x1202] = new("SetPCToddler", false, 1, [1], true),
            [0x1203] = new("IsCombatTarget", true, 1, [6], true),
            [0x1204] = new("RewardKarma", false, 1, [1], true),
            [0x120b] = new("IsPS3", false, 0, [], true),
            [0x120c] = new("IsWin32", false, 0, [], true),
            [0x1217] = new("ForceSave", false, 0, [], true),
            [0x1218] = new("SetSPECIALPoints", false, 1, [1], true),
            [0x121a] = new("SetTagSkills", false, 1, [1, 1], true),
            [0x1222] = new("GetQuestCompleted", false, 1, [14], true),
            [0x1224] = new("PipBoyRadioOff", false, 0, [], true),
            [0x1241] = new("ClearScreenSplatter", false, 0, [], true),
            [0x1268] = new("traitmenu", false, 0, [], true),
            [0x126d] = new("resetxp", true, 0, [], true),
            [0x127f] = new("GetInCharGen", false, 0, [], true),
        };

    internal static FalloutCompiledCommandDeclaration Get(ushort opcode) =>
        Commands.TryGetValue(opcode, out var declaration) ? declaration :
            throw new NotSupportedException($"Compiled command opcode {opcode:x4} has no proven declaration.");

    internal static FalloutCompiledCommandDeclaration Get(ushort opcode, FalloutPluginStack records)
    {
        if (records.OwnedSource is not { } source) return Get(opcode);
        var catalogue = SourceCommands.GetValue(source, owner =>
            FalloutExecutableStringTable.ReadScriptCommandDeclarations(owner.FalloutExecutablePath));
        if (!catalogue.Commands.TryGetValue(opcode, out var declaration))
            throw new NotSupportedException($"Compiled command opcode {opcode:x4} has no selected executable declaration.");
        return new(declaration.Name, declaration.RequiresReference, declaration.Required,
            declaration.Parameters, declaration.VanillaArguments);
    }
}
