#pragma once
#include <array>
#include <cstdint>
#include <memory>

namespace opennv_domain {
enum class NvseDataCall : std::uint32_t {
    input_create = 1, input_exchange = 2, function = 3, inventory_create = 4,
    inventory_get = 5, inventory_self = 6, lambda_save = 7, lambda_unsave = 8,
    is_lambda = 9, singleton = 10, data = 11, clear_cache = 12
};
struct NvseDiKey {
    std::uint8_t raw, game, inserted, hold, tap, user_disabled, script_disabled;
};
static_assert(sizeof(NvseDiKey) == 7);
// Public JIP/xNVSE key-prefix layout. The vtable/destructor are generated by
// this first-party constructor. Native buffered-device queues are not exposed.
struct NvseDiObject {
    virtual ~NvseDiObject() = default;
    std::array<NvseDiKey, 266> keys{};
};
static_assert(sizeof(NvseDiObject) == 0x74c);
struct NvseDataInterface {
    std::uint32_t version;
    void* (__cdecl* singleton)(std::uint32_t);
    void* (__cdecl* function)(std::uint32_t);
    void* (__cdecl* data)(std::uint32_t);
    void (__cdecl* clear_cache)();
};
static_assert(sizeof(NvseDataInterface) == 20);
struct NvseDataRuntime {
    NvseDataInterface table{};
    std::unique_ptr<NvseDiObject> input;
    std::uint64_t window = 0, sample = 0, sequence = 0;
    std::uint32_t input_vtable = 0;
    std::int64_t revision = 0;
    bool synchronizing = false;
};
}
